name: 'testing called'

on:
  workflow_call:

jobs:
  checkout-testing:
    runs-on: ubuntu-latest

    steps:
 
      - name: checkout called
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: List all files and directories
        run: |
          echo "Listing all files and directories:"
          ls -R
      - name: List all files and directories in a specific directory
        run: |
          echo "Listing all files and directories in .github:"
          ls -R .github

      - name: Use custom action
        uses: ./.github/actions/test2
      - name: Use custom actions
        uses: kpking1902/called/.github/actions/test@main
  