name: 'testing called'

on:
  workflow_call:

jobs:
  checkout-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout caller repository
        uses: actions/checkout@v4
        with:
          repository: kpking1902/caller
          path: caller

      - name: Use custom action
        uses: ./caller/.github/actions/test2
      - name: use called action
        uses: .github/actions/test