name: 'testing called'

on:
  workflow_call:

jobs:
  checkout-testing:
    runs-on: ubuntu-latest

    steps:
 
      - name: checkout called
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: List files in actions directory
        run: |
          ls -R .github/actions 
      - name: Use custom action
        uses: ./.github/actions/test2
      - name: Use custom actions
        uses: kpking1902/called/.github/actions/test@main
  