name: 'testing called'

on:
  workflow_call:

jobs:
  checkout-testing:
    runs-on: ubuntu-latest

    # steps:
 
    #   - name: checkout called
    #     uses: actions/checkout@v4
    #     with:
    #       fetch-depth: 0
    #   - name: Use custom action
    #     uses: ./.github/actions/test2 
    #   - name: Use custom actions
    #     uses: kpking1902/called/.github/actions/test@main
    steps:
      - name: Checkout caller repository
        uses: actions/checkout@v4
        with:
          repository: kpking1902/caller
          path: caller

      - name: Use custom action
        uses: ./caller/.github/actions/test2
      - name: using called
        uses: ./.github/actions/test