name: 'testing called'

on:
  workflow_call:

jobs:
  checkout-testing:
    runs-on: ubuntu-latest

    steps:
 
      - name: checkout called
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Run test.py script
        run: |
          python kpking1902/called/test.py@main

      - name: Run test.py script
        run: |
          python called/test.py
 
      - name: Use custom action
        uses: ./.github/actions/test2
      - name: Use custom actions
        uses: kpking1902/called/.github/actions/test@main
  